openapi: 3.0.2
info:
  contact:
    email: info@example.org
    name: Acme Corporation
    url: http://example.org/
  description: add description, please
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  title: a minimal sample OGC API - EDR implementation
  version: 1.0.0
servers:
- description: Production server
  url: https://data.example.org/
- description: Development server
  url: https://dev.example.org/
tags:
- description: essential characteristics of this API
  name: Capabilities
- description: access to data (features)
  name: Data
paths:
  /:
    get:
      description: |-
        The landing page provides links to the API definition, the conformance
        statements and to the feature collections in this dataset.
      operationId: get_landing_page
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/landingPage'
          description: |-
            The landing page provides links to the API definition
            (link relations `service-desc` and `service-doc`),
            the Conformance declaration (path `/conformance`,
            link relation `conformance`), and the Feature
            Collections (path `/collections`, link relation
            `data`).
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
      summary: landing page
      tags:
      - Capabilities
      x-openapi-router-controller: openapi_server.controllers.capabilities_controller
  /collections:
    get:
      operationId: get_collections
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/collections'
          description: |-
            The feature collections shared by this API.

            The dataset is organized as one or more feature collections. This resource
            provides information about and access to the collections.

            The response contains the list of collections. For each collection, a link
            to the items in the collection (path `/collections/{collectionId}/items`,
            link relation `items`) as well as key information about the collection.
            This information includes:

            * A local identifier for the collection that is unique for the dataset;
            * A list of coordinate reference systems (CRS) in which geometries may be returned by the server. The first CRS is the default coordinate reference system (the default is always WGS 84 with axis order longitude/latitude);
            * An optional title and description for the collection;
            * An optional extent that can be used to provide an indication of the spatial and temporal extent of the collection - typically derived from the data;
            * An optional indicator about the type of the items in the collection (the default value, if the indicator is not provided, is 'feature').
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
      summary: the feature collections in the dataset
      tags:
      - Capabilities
      x-openapi-router-controller: openapi_server.controllers.capabilities_controller
  /collections/{collectionId}:
    get:
      operationId: describe_collection
      parameters:
      - description: local identifier of a collection
        explode: false
        in: path
        name: collectionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/confClasses'
          description: |-
            Information about the feature collection with id `collectionId`.

            The response contains a link to the items in the collection
            (path `/collections/{collectionId}/items`, link relation `items`)
            as well as key information about the collection. This information
            includes:

            * A local identifier for the collection that is unique for the dataset;
            * A list of coordinate reference systems (CRS) in which geometries may be returned by the server. The first CRS is the default coordinate reference system (the default is always WGS 84 with axis order longitude/latitude);
            * An optional title and description for the collection;
            * An optional extent that can be used to provide an indication of the spatial and temporal extent of the collection - typically derived from the data;
            * An optional indicator about the type of the items in the collection (the default value, if the indicator is not provided, is 'feature').
        "404":
          description: The requested resource does not exist on the server. For example,
            a path parameter had an incorrect value.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
          description: A server error occurred.
      summary: describe the feature collection with id `collectionId`
      tags:
      - Capabilities
      x-openapi-router-controller: openapi_server.controllers.capabilities_controller
  /collections/{collectionId}/instances:
    get:
      description: This will provide list of the avalable instances of the collection
        Use content negotiation to request HTML or JSON.
      operationId: get_collection_instances
      parameters:
      - description: local identifier of a collection
        explode: false
        in: path
        name: collectionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/instances'
          description: Metadata about the instance of {collectionId} collection shared
            by this API.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
          description: An error occured.
      summary: List data instances of {collectionId}
      tags:
      - Collection metadata
      x-openapi-router-controller: openapi_server.controllers.collection_metadata_controller
  /collections/{collectionId}/instances/{instanceId}/radius:
    get:
      description: Query end point to return all data within a defined radius of the
        defined point location queries
      operationId: get_instance_data_for_radius
      parameters:
      - description: local identifier of a collection
        explode: false
        in: path
        name: collectionId
        required: true
        schema:
          type: string
        style: simple
      - description: local identifier of a collection
        explode: false
        in: path
        name: instanceId
        required: true
        schema:
          type: string
        style: simple
      - description: radius
        explode: true
        in: query
        name: within
        required: true
        schema:
          type: number
        style: form
      - description: Distance units for the corridor-width parameter (e.g KM)
        explode: true
        in: query
        name: within-units
        required: true
        schema:
          type: string
        style: form
      - description: "location(s) to return data for, the coordinates are defined\
          \ by a Well Known Text\n(wkt) string. to retrieve a single location :\n\n\
          POINT(x y) i.e. POINT(0 51.48) for Greenwich, London\n\nsee http://portal.opengeospatial.org/files/?artifact_id=25355\
          \ and \nhttps://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry\n\
          \nthe coordinate values will depend on the CRS parameter, if this is not\
          \ defined\nthe values will be assumed to WGS84 values (i.e x=longitude and\
          \ y=latitude)\n"
        explode: true
        in: query
        name: radiusCoords
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/geo+json:
              schema:
                $ref: '#/components/schemas/featureCollectionGeoJSON'
          description: Data ranges required to construct valid queries for the choosen
            data collection
        "202":
          description: Data request still being processed
        "308":
          description: Request will take a significant time to process
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
          description: Invalid request.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
          description: Requested data not found.
        "413":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
          description: Requested data volume to large to be handled by this service.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
          description: An error occured.
      summary: Query end point to return data within defined radius of a point for
        an instance {instanceId} of collection {collectionId}
      tags:
      - Instance data queries
      x-openapi-router-controller: openapi_server.controllers.instance_data_queries_controller
  /conformance:
    get:
      description: |-
        A list of all conformance classes specified in a standard that the
        server conforms to.
      operationId: get_conformance_declaration
      responses:
        "200":
          content:
            application/json:
              example:
                conformsTo:
                - http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core
                - http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30
                - http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/html
                - http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson
              schema:
                $ref: '#/components/schemas/confClasses'
          description: |-
            The URIs of all conformance classes supported by the server.

            To support "generic" clients that want to access multiple
            OGC API Features implementations - and not "just" a specific
            API / server, the server declares the conformance
            classes it implements and conforms to.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
          description: A server error occurred.
      summary: information about specifications that this API conforms to
      tags:
      - Capabilities
      x-openapi-router-controller: openapi_server.controllers.capabilities_controller
components:
  schemas:
    landingPage:
      example:
        description: description
        links:
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: title
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: title
        title: title
      properties:
        title:
          title: title
          type: string
        description:
          title: description
          type: string
        links:
          items:
            $ref: '#/components/schemas/link'
          title: links
          type: array
      required:
      - links
      title: landingPage
      type: object
    link:
      example:
        hreflang: en
        rel: alternate
        length: 0
        href: http://data.example.com/buildings/123
        type: application/geo+json
        title: title
      properties:
        href:
          example: http://data.example.com/buildings/123
          title: href
          type: string
        rel:
          example: alternate
          title: rel
          type: string
        type:
          example: application/geo+json
          title: type
          type: string
        hreflang:
          example: en
          title: hreflang
          type: string
        title:
          title: title
          type: string
        length:
          title: length
          type: integer
      required:
      - href
      title: link
      type: object
    exception:
      description: 'Information about the exception: an error code plus an optional
        description.'
      properties:
        code:
          title: code
          type: string
        description:
          title: description
          type: string
      required:
      - code
      title: exception
      type: object
    confClasses:
      example:
        conformsTo:
        - conformsTo
        - conformsTo
      properties:
        conformsTo:
          items:
            type: string
          title: conformsTo
          type: array
      required:
      - conformsTo
      title: confClasses
      type: object
    collections:
      example:
        collections:
        - extent:
            spatial:
              crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
              bbox:
              - - -180
                - -90
                - 180
                - 90
              - - -180
                - -90
                - 180
                - 90
            temporal:
              trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
              interval:
              - - 2011-11-11T12:22:11Z
                - null
              - - 2011-11-11T12:22:11Z
                - null
          itemType: feature
          parameter_names:
            key: '{}'
          keywords:
          - keywords
          - keywords
          crs:
          - crs
          - crs
          output_formats:
          - CoverageJSON
          - GeoJSON
          - IWXXM
          - GRIB
          description: An address.
          links:
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
          id: address
          title: address
          data_queries:
            area:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            corridor:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            locations:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            position:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            cube:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            radius:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            trajectory:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            items:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
        - extent:
            spatial:
              crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
              bbox:
              - - -180
                - -90
                - 180
                - 90
              - - -180
                - -90
                - 180
                - 90
            temporal:
              trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
              interval:
              - - 2011-11-11T12:22:11Z
                - null
              - - 2011-11-11T12:22:11Z
                - null
          itemType: feature
          parameter_names:
            key: '{}'
          keywords:
          - keywords
          - keywords
          crs:
          - crs
          - crs
          output_formats:
          - CoverageJSON
          - GeoJSON
          - IWXXM
          - GRIB
          description: An address.
          links:
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
          id: address
          title: address
          data_queries:
            area:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            corridor:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            locations:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            position:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            cube:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            radius:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            trajectory:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            items:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
        links:
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: title
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: title
      properties:
        links:
          items:
            $ref: '#/components/schemas/link'
          title: links
          type: array
        collections:
          items:
            $ref: '#/components/schemas/collection'
          title: collections
          type: array
      required:
      - collections
      - links
      title: collections
      type: object
    collection:
      example:
        extent:
          spatial:
            crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            bbox:
            - - -180
              - -90
              - 180
              - 90
            - - -180
              - -90
              - 180
              - 90
          temporal:
            trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
            interval:
            - - 2011-11-11T12:22:11Z
              - null
            - - 2011-11-11T12:22:11Z
              - null
        itemType: feature
        parameter_names:
          key: '{}'
        keywords:
        - keywords
        - keywords
        crs:
        - crs
        - crs
        output_formats:
        - CoverageJSON
        - GeoJSON
        - IWXXM
        - GRIB
        description: An address.
        links:
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: title
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: title
        id: address
        title: address
        data_queries:
          area:
            link:
              hreflang: en
              rel: alternate
              length: 0
              href: http://data.example.com/buildings/123
              type: application/geo+json
              title: title
          corridor:
            link:
              hreflang: en
              rel: alternate
              length: 0
              href: http://data.example.com/buildings/123
              type: application/geo+json
              title: title
          locations:
            link:
              hreflang: en
              rel: alternate
              length: 0
              href: http://data.example.com/buildings/123
              type: application/geo+json
              title: title
          position:
            link:
              hreflang: en
              rel: alternate
              length: 0
              href: http://data.example.com/buildings/123
              type: application/geo+json
              title: title
          cube:
            link:
              hreflang: en
              rel: alternate
              length: 0
              href: http://data.example.com/buildings/123
              type: application/geo+json
              title: title
          radius:
            link:
              hreflang: en
              rel: alternate
              length: 0
              href: http://data.example.com/buildings/123
              type: application/geo+json
              title: title
          trajectory:
            link:
              hreflang: en
              rel: alternate
              length: 0
              href: http://data.example.com/buildings/123
              type: application/geo+json
              title: title
          items:
            link:
              hreflang: en
              rel: alternate
              length: 0
              href: http://data.example.com/buildings/123
              type: application/geo+json
              title: title
      properties:
        id:
          description: identifier of the collection used, for example, in URIs
          example: address
          title: id
          type: string
        title:
          description: human readable title of the collection
          example: address
          title: title
          type: string
        description:
          description: a description of the features in the collection
          example: An address.
          title: description
          type: string
        links:
          items:
            $ref: '#/components/schemas/link'
          title: links
          type: array
        keywords:
          description: List of keywords which help to describe the collection
          items:
            type: string
          title: keywords
          type: array
        extent:
          $ref: '#/components/schemas/extent'
        itemType:
          default: feature
          description: indicator about the type of the items in the collection (the
            default value is 'feature').
          title: itemType
          type: string
        crs:
          default:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          description: the list of coordinate reference systems supported by the service
          items:
            type: string
          title: crs
          type: array
        data_queries:
          $ref: '#/components/schemas/collection_data_queries'
        output_formats:
          description: list of formats the results can be presented in
          example:
          - CoverageJSON
          - GeoJSON
          - IWXXM
          - GRIB
          items:
            type: string
          title: output_formats
          type: array
        parameter_names:
          description: list of the data parameters available in the collection
          title: parameter_names
          type: object
      required:
      - extent
      - id
      - links
      - parameter_names
      title: collection
      type: object
    extent:
      description: |-
        The extent of the features in the collection. In the Core only spatial and temporal
        extents are specified. Extensions may add additional members to represent other
        extents, for example, thermal or pressure ranges.
      example:
        spatial:
          crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
          bbox:
          - - -180
            - -90
            - 180
            - 90
          - - -180
            - -90
            - 180
            - 90
        temporal:
          trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
          interval:
          - - 2011-11-11T12:22:11Z
            - null
          - - 2011-11-11T12:22:11Z
            - null
      properties:
        spatial:
          $ref: '#/components/schemas/extent_spatial'
        temporal:
          $ref: '#/components/schemas/extent_temporal'
      title: extent
      type: object
    featureCollectionGeoJSON:
      example:
        timeStamp: 2017-08-17T08:05:32Z
        features:
        - links:
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
          id: id
          type: Feature
          properties: '{}'
        - links:
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
          id: id
          type: Feature
          properties: '{}'
        numberReturned: 10
        links:
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: title
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: title
        type: FeatureCollection
        numberMatched: 127
        parameters: '{}'
      properties:
        type:
          enum:
          - FeatureCollection
          title: type
          type: string
        features:
          items:
            $ref: '#/components/schemas/featureGeoJSON'
          title: features
          type: array
        links:
          items:
            $ref: '#/components/schemas/link'
          title: links
          type: array
        timeStamp:
          description: This property indicates the time and date when the response
            was generated.
          example: 2017-08-17T08:05:32Z
          format: date-time
          title: timeStamp
          type: string
        numberMatched:
          description: |-
            The number of features of the feature type that match the selection
            parameters like `bbox`.
          example: 127
          minimum: 0
          title: numberMatched
          type: integer
        numberReturned:
          description: |-
            The number of features in the feature collection.

            A server may omit this information in a response, if the information
            about the number of features is not known or difficult to compute.

            If the value is provided, the value shall be identical to the number
            of items in the "features" array.
          example: 10
          minimum: 0
          title: numberReturned
          type: integer
        parameters:
          description: observed parameters
          title: parameters
          type: object
      required:
      - features
      - type
      title: featureCollectionGeoJSON
      type: object
    featureGeoJSON:
      example:
        links:
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: title
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: title
        id: id
        type: Feature
        properties: '{}'
      properties:
        type:
          enum:
          - Feature
          title: type
          type: string
        geometry:
          $ref: '#/components/schemas/geometryGeoJSON'
        properties:
          nullable: true
          title: properties
          type: object
        id:
          title: id
          type: string
        links:
          items:
            $ref: '#/components/schemas/link'
          title: links
          type: array
      required:
      - geometry
      - properties
      - type
      title: featureGeoJSON
      type: object
    geometryGeoJSON:
      oneOf:
      - $ref: '#/components/schemas/pointGeoJSON'
      - $ref: '#/components/schemas/multipointGeoJSON'
      - $ref: '#/components/schemas/linestringGeoJSON'
      - $ref: '#/components/schemas/multilinestringGeoJSON'
      - $ref: '#/components/schemas/polygonGeoJSON'
      - $ref: '#/components/schemas/multipolygonGeoJSON'
      - $ref: '#/components/schemas/geometrycollectionGeoJSON'
      title: geometryGeoJSON
    pointGeoJSON:
      properties:
        type:
          enum:
          - Point
          type: string
        coordinates:
          items:
            type: number
          minItems: 2
          type: array
      required:
      - coordinates
      - type
      type: object
    multipointGeoJSON:
      properties:
        type:
          enum:
          - MultiPoint
          type: string
        coordinates:
          items:
            items:
              type: number
            minItems: 2
            type: array
          type: array
      required:
      - coordinates
      - type
      type: object
    linestringGeoJSON:
      properties:
        type:
          enum:
          - LineString
          type: string
        coordinates:
          items:
            items:
              type: number
            minItems: 2
            type: array
          minItems: 2
          type: array
      required:
      - coordinates
      - type
      type: object
    multilinestringGeoJSON:
      properties:
        type:
          enum:
          - MultiLineString
          type: string
        coordinates:
          items:
            items:
              items:
                type: number
              minItems: 2
              type: array
            minItems: 2
            type: array
          type: array
      required:
      - coordinates
      - type
      type: object
    polygonGeoJSON:
      properties:
        type:
          enum:
          - Polygon
          type: string
        coordinates:
          items:
            items:
              items:
                type: number
              minItems: 2
              type: array
            minItems: 4
            type: array
          type: array
      required:
      - coordinates
      - type
      type: object
    multipolygonGeoJSON:
      properties:
        type:
          enum:
          - MultiPolygon
          type: string
        coordinates:
          items:
            items:
              items:
                items:
                  type: number
                minItems: 2
                type: array
              minItems: 4
              type: array
            type: array
          type: array
      required:
      - coordinates
      - type
      type: object
    geometrycollectionGeoJSON:
      properties:
        type:
          enum:
          - GeometryCollection
          type: string
        geometries:
          items:
            $ref: '#/components/schemas/geometryGeoJSON'
          type: array
      required:
      - geometries
      - type
      type: object
    timeStamp:
      description: This property indicates the time and date when the response was
        generated.
      example: 2017-08-17T08:05:32Z
      format: date-time
      title: timeStamp
      type: string
    numberMatched:
      description: |-
        The number of features of the feature type that match the selection
        parameters like `bbox`.
      example: 127
      minimum: 0
      title: numberMatched
      type: integer
    numberReturned:
      description: |-
        The number of features in the feature collection.

        A server may omit this information in a response, if the information
        about the number of features is not known or difficult to compute.

        If the value is provided, the value shall be identical to the number
        of items in the "features" array.
      example: 10
      minimum: 0
      title: numberReturned
      type: integer
    extent_spatial:
      description: The spatial extent of the features in the collection.
      example:
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        bbox:
        - - -180
          - -90
          - 180
          - 90
        - - -180
          - -90
          - 180
          - 90
      properties:
        bbox:
          description: |-
            One or more bounding boxes that describe the spatial extent of the dataset.
            In the Core only a single bounding box is supported. Extensions may support
            additional areas. If multiple areas are provided, the union of the bounding
            boxes describes the spatial extent.
          items:
            description: |-
              Each bounding box is provided as four or six numbers, depending on
              whether the coordinate reference system includes a vertical axis
              (height or depth):

              * Lower left corner, coordinate axis 1
              * Lower left corner, coordinate axis 2
              * Minimum value, coordinate axis 3 (optional)
              * Upper right corner, coordinate axis 1
              * Upper right corner, coordinate axis 2
              * Maximum value, coordinate axis 3 (optional)

              The coordinate reference system of the values is WGS 84 longitude/latitude
              (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a different coordinate
              reference system is specified in `crs`.

              For WGS 84 longitude/latitude the values are in most cases the sequence of
              minimum longitude, minimum latitude, maximum longitude and maximum latitude.
              However, in cases where the box spans the antimeridian the first value
              (west-most box edge) is larger than the third value (east-most box edge).

              If the vertical axis is included, the third and the sixth number are
              the bottom and the top of the 3-dimensional bounding box.

              If a feature has multiple spatial geometry properties, it is the decision of the
              server whether only a single spatial geometry property is used to determine
              the extent or all relevant geometries.
            example:
            - -180
            - -90
            - 180
            - 90
            items:
              type: number
            type: array
          minItems: 1
          title: bbox
          type: array
        crs:
          default: http://www.opengis.net/def/crs/OGC/1.3/CRS84
          description: |-
            Coordinate reference system of the coordinates in the spatial extent
            (property `bbox`). The default reference system is WGS 84 longitude/latitude.
            In the Core this is the only supported coordinate reference system.
            Extensions may support additional coordinate reference systems and add
            additional enum values.
          enum:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          title: crs
          type: string
      title: extent_spatial
      type: object
    extent_temporal:
      description: The temporal extent of the features in the collection.
      example:
        trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
        interval:
        - - 2011-11-11T12:22:11Z
          - null
        - - 2011-11-11T12:22:11Z
          - null
      properties:
        interval:
          description: |-
            One or more time intervals that describe the temporal extent of the dataset.
            The value `null` is supported and indicates an open time interval.
            In the Core only a single time interval is supported. Extensions may support
            multiple intervals. If multiple intervals are provided, the union of the
            intervals describes the temporal extent.
          items:
            description: |-
              Begin and end times of the time interval. The timestamps are in the
              temporal coordinate reference system specified in `trs`. By default
              this is the Gregorian calendar.
            example:
            - 2011-11-11T12:22:11Z
            - null
            items:
              format: date-time
              nullable: true
              type: string
            maxItems: 2
            minItems: 2
            type: array
          minItems: 1
          title: interval
          type: array
        trs:
          default: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
          description: |-
            Coordinate reference system of the coordinates in the temporal extent
            (property `interval`). The default reference system is the Gregorian calendar.
            In the Core this is the only supported temporal coordinate reference system.
            Extensions may support additional temporal coordinate reference systems and add
            additional enum values.
          enum:
          - http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
          title: trs
          type: string
      title: extent_temporal
      type: object
    instances:
      example:
        instances:
        - extent:
            spatial:
              crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
              bbox:
              - - -180
                - -90
                - 180
                - 90
              - - -180
                - -90
                - 180
                - 90
            temporal:
              trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
              interval:
              - - 2011-11-11T12:22:11Z
                - null
              - - 2011-11-11T12:22:11Z
                - null
          itemType: feature
          parameter_names:
            key: '{}'
          keywords:
          - keywords
          - keywords
          crs:
          - crs
          - crs
          output_formats:
          - CoverageJSON
          - GeoJSON
          - IWXXM
          - GRIB
          description: An address.
          links:
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
          id: address
          title: address
          data_queries:
            area:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            corridor:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            locations:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            position:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            cube:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            radius:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            trajectory:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            items:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
        - extent:
            spatial:
              crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
              bbox:
              - - -180
                - -90
                - 180
                - 90
              - - -180
                - -90
                - 180
                - 90
            temporal:
              trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
              interval:
              - - 2011-11-11T12:22:11Z
                - null
              - - 2011-11-11T12:22:11Z
                - null
          itemType: feature
          parameter_names:
            key: '{}'
          keywords:
          - keywords
          - keywords
          crs:
          - crs
          - crs
          output_formats:
          - CoverageJSON
          - GeoJSON
          - IWXXM
          - GRIB
          description: An address.
          links:
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
          id: address
          title: address
          data_queries:
            area:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            corridor:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            locations:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            position:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            cube:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            radius:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            trajectory:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
            items:
              link:
                hreflang: en
                rel: alternate
                length: 0
                href: http://data.example.com/buildings/123
                type: application/geo+json
                title: title
        links:
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: title
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: title
      properties:
        links:
          items:
            $ref: '#/components/schemas/link'
          title: links
          type: array
        instances:
          items:
            $ref: '#/components/schemas/collection'
          title: instances
          type: array
      required:
      - instances
      - links
      title: instances
      type: object
    collection_data_queries_position:
      example:
        link:
          hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: title
      properties:
        link:
          $ref: '#/components/schemas/link'
      title: collection_data_queries_position
      type: object
    collection_data_queries:
      description: Detailed information relevant to individual query types
      example:
        area:
          link:
            hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
        corridor:
          link:
            hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
        locations:
          link:
            hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
        position:
          link:
            hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
        cube:
          link:
            hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
        radius:
          link:
            hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
        trajectory:
          link:
            hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
        items:
          link:
            hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: title
      properties:
        position:
          $ref: '#/components/schemas/collection_data_queries_position'
        radius:
          $ref: '#/components/schemas/collection_data_queries_position'
        area:
          $ref: '#/components/schemas/collection_data_queries_position'
        cube:
          $ref: '#/components/schemas/collection_data_queries_position'
        trajectory:
          $ref: '#/components/schemas/collection_data_queries_position'
        corridor:
          $ref: '#/components/schemas/collection_data_queries_position'
        locations:
          $ref: '#/components/schemas/collection_data_queries_position'
        items:
          $ref: '#/components/schemas/collection_data_queries_position'
      title: collection_data_queries
      type: object
